name: keyboard-eyelash-corne

permissions:
  contents: read

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'keyboards/eyelash_corne/**'
      - 'keyboards/lib/**'
      - 'keyboards/Makefile'
      - '.github/workflows/build-keyboard-eyelash-corne.yaml'
  push:
    branches:
      - main
    paths:
      - 'keyboards/eyelash_corne/**'
      - 'keyboards/lib/**'
      - 'keyboards/Makefile'
      - '.github/workflows/build-keyboard-eyelash-corne.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-keyboard-eyelash-corne
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Build eyelash_corne firmware
        run: |
          make keyboards/eyelash_corne/build
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: eyelash_corne-firmware
          path: keyboards/eyelash_corne/firmwares/eyelash_corne_*.uf2
          if-no-files-found: error
