name: keyboard-eyelash-corne

permissions:
  contents: read

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'keyboards/eyelash_corne/**'
      - 'keyboards/lib/**'
      - 'keyboards/Makefile'
      - '.github/workflows/build-keyboard-eyelash-corne.yaml'
  push:
    branches:
      - main
    paths:
      - 'keyboards/eyelash_corne/**'
      - 'keyboards/lib/**'
      - 'keyboards/Makefile'
      - '.github/workflows/build-keyboard-eyelash-corne.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-keyboard-eyelash-corne
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build eyelash_corne firmware
        run: |
          make eyelash_corne/build
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v5
        with:
          name: eyelash_corne-firmware
          path: keyboards/firmwares/eyelash_corne_*.uf2
          if-no-files-found: error
