name: keyboard-moonlander

permissions:
  contents: read

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'keyboards/moonlander/**'
      - 'keyboards/lib/**'
      - '.github/workflows/build-keyboard-moonlander.yaml'
  push:
    branches:
      - main
    paths:
      - 'keyboards/moonlander/**'
      - 'keyboards/lib/**'
      - '.github/workflows/build-keyboard-moonlander.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-keyboard-moonlander
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build moonlander firmware
        run: |
          make keyboards/moonlander/update keyboards/moonlander/build
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: moonlander-firmware
          path: keyboards/moonlander/build/zsa_moonlander_vincent.bin
          if-no-files-found: error
